services:

  app:
    build:
      context: ./backend/docker
      dockerfile: Dockerfile
    container_name: yandex_app
    restart: unless-stopped
    working_dir: /var/www
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    shm_size: '2gb'
    ports:
      - "8000:80"
    volumes:
      - ./backend/:/var/www
      - ./backend/local-php.ini:/usr/local/etc/php/conf.d/local-php.ini
    env_file:
      - backend/.env
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  queue-worker:
    build:
      context: ./backend/docker
      dockerfile: Dockerfile
    container_name: yandex_worker
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan queue:work database --queue=default --sleep=3 --tries=3 --timeout=600
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    shm_size: '2gb'
    volumes:
      - ./backend/:/var/www
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: yandex_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./backend/.env
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: yandex_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

  reverb:
    build:
      context: ./backend/docker
      dockerfile: Dockerfile
    container_name: yandex_reverb
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    volumes:
      - ./backend:/var/www
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
