services:

  app:
    build:
      context: ./backend/docker
      dockerfile: Dockerfile
    container_name: yandex_app
    restart: unless-stopped
    working_dir: /var/www
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    shm_size: '2gb'
    ports:
      - "8000:80"
    volumes:
      - ./backend/docker/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/docker/nginx.conf:/etc/nginx/conf.d/uploads.conf
      - ./backend/docker/php.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./backend:/var/www
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  queue-worker:
    build:
      context: ./backend/docker
      dockerfile: Dockerfile
    container_name: yandex_worker
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan queue:work --queue=default,reverb --sleep=3 --tries=3 --timeout=600
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    shm_size: '2gb'
    volumes:
      - ./backend:/var/www
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: yandex_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"       # Порт для обмена сообщениями
      - "15672:15672"     # Веб-панель управления
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - ./backend/.env
    depends_on:
        - queue-worker
        - reverb
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: yandex_mysql
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: yandex_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

  reverb:
    build:
      context: ./backend/docker
      dockerfile: Dockerfile
    container_name: yandex_reverb
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    volumes:
      - ./backend:/var/www
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  app-network:
    driver: bridge