server {
    listen 80;
    index index.html;
    root /var/www/frontend/dist;

    # Фронтенд
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Бэкенд API
    location /api {
        # 'laravel-app' — имя сервиса бэкенда из docker-compose
        proxy_pass http://app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}